#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

GULPSCRIPT="
#!/bin/bash

cd /app
PATH=\$PATH:/app/vendor/node/bin
if [[ -f ./gulpfile.js ]]; then
	npm install -g gulp && gulp build
fi
"

echo '-----> Injecting gulp script'
id=$(echo "$GULPSCRIPT" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.gulp")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run -d $IMAGE /bin/bash -c "chmod +x /app/.gulp")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
